[workspace]
members = [
    "day_01_puzzle_01",
    "day_01_puzzle_02",
    "day_02_puzzle_01",
    "day_02_puzzle_02",
    "day_03_puzzle_01",
    "day_03_puzzle_02",
    "day_04_puzzle_01",
    "day_04_puzzle_02",
    "day_05_puzzle_01",
]